name: Build rping exe

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build release
        run: cargo build --release
      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: rping-exe
          path: target/release/rnp.exe
